# Generated by Django 5.0.6 on 2024-07-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movielist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('sports', 'Sports'), ('reality_series', 'Reality Series'), ('science_fiction', 'Science Fiction'), ('fantasy', 'Fantasy')], max_length=100),
        ),
    ]
