# Generated by Django 5.0.6 on 2024-07-12 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movie_youtube_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
    ]
