# Generated by Django 5.0.6 on 2024-07-16 23:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_custommovielist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movielist',
            unique_together={('owner_user', 'name')},
        ),
    ]
